### ISSUE TITLE
建议增加项目名称的选填项

### ISSUE THREAD

**Issue by kaminaning** [xusenlin/marewood#12]
现在的url都是指向webs/1 之类的文件夹，建议增加项目名称的选填项，可以自定义子文件夹的名称，美化url

**Comment by xusenlin** [comment]
> 现在的url都是指向webs/1 之类的文件夹，建议增加项目名称的选填项，可以自定义子文件夹的名称，美化url

任务现在可以添加别名了，对应url的目录
