### ISSUE TITLE
本地mac系统打包后，部署到linux服务器上，资源目录错误

### ISSUE THREAD

**Issue by sakula92** [xusenlin/marewood#14]
启动错误日志中显示的是本地mac电脑的路径

![image](https://user-images.githubusercontent.com/22268169/147028874-e7307308-08cd-4536-a0d8-9f5348f6922a.png)

**Comment by sakula92** [comment]
是不是不可以这么做，还有需要其他配置0.0

**Comment by xusenlin** [comment]
> 是不是不可以这么做，还有需要其他配置0.0

我之前在我的mac上也是出现这种问题，可能是交叉编译的问题，后面我都是放到服务器上编译了。
