### ISSUE TITLE
不为我正常工作

### ISSUE THREAD

**Issue by P2K0** [xusenlin/marewood#15]
![image](https://github.com/xusenlin/marewood/assets/39264625/9ee67476-2775-4713-a0f9-d45c25615d33)
![image](https://github.com/xusenlin/marewood/assets/39264625/7290ac37-2282-47e6-bd88-82d65fa1b54e)

open /marewood/resources/repositories/1/package.json: no such file or directory

**Comment by xusenlin** [comment]
> ![image](https://private-user-images.githubusercontent.com/39264625/295094319-9ee67476-2775-4713-a0f9-d45c25615d33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTQ2NjYsIm5iZiI6MTcwNDg1NDM2NiwicGF0aCI6Ii8zOTI2NDYyNS8yOTUwOTQzMTktOWVlNjc0NzYtMjc3NS00NzEzLWEwZjktZDQ1YzI1NjE1ZDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyMzkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NWE2MzQ3MGI1ZWNhMzdlOWEyODVmNGQ2NWEzZDFmNWZiZmRlM2NiMjA3Yjk5ZmNhYTFiMjEzYzY0ZjM4ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.29ndOTfDqjKGetM_hTn6gtQOeQvcGaWXTqO3uCcyixY) ![image](https://private-user-images.githubusercontent.com/39264625/295094499-7290ac37-2282-47e6-bd88-82d65fa1b54e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTQ2NjYsIm5iZiI6MTcwNDg1NDM2NiwicGF0aCI6Ii8zOTI2NDYyNS8yOTUwOTQ0OTktNzI5MGFjMzctMjI4Mi00N2U2LWJkODgtODJkNjVmYTFiNTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyMzkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YmU4ZDU4NmM5NWEwNWQwODRjMDQyMWUxMGUzZjdkOTBjMDVjMzA3Y2U1NDEyMjU1NjllMTU1MmI2ZjA3ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VkjBcPv18BuPyC_OGoSnS_keOrcTroWrjZ_28Nm7uT8)
> 
> open /marewood/resources/repositories/1/package.json: no such file or directory

你的前端项目(仓库id1)下是否有 package.json 文件？marewood 需要解析这个文件，才能提供打包命令给你选择。

**Comment by P2K0** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/39264625/295094319-9ee67476-2775-4713-a0f9-d45c25615d33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTQ2NjYsIm5iZiI6MTcwNDg1NDM2NiwicGF0aCI6Ii8zOTI2NDYyNS8yOTUwOTQzMTktOWVlNjc0NzYtMjc3NS00NzEzLWEwZjktZDQ1YzI1NjE1ZDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyMzkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NWE2MzQ3MGI1ZWNhMzdlOWEyODVmNGQ2NWEzZDFmNWZiZmRlM2NiMjA3Yjk5ZmNhYTFiMjEzYzY0ZjM4ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.29ndOTfDqjKGetM_hTn6gtQOeQvcGaWXTqO3uCcyixY) ![图像](https://private-user-images.githubusercontent.com/39264625/295094499-7290ac37-2282-47e6-bd88-82d65fa1b54e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTQ2NjYsIm5iZiI6MTcwNDg1NDM2NiwicGF0aCI6Ii8zOTI2NDYyNS8yOTUwOTQ0OTktNzI5MGFjMzctMjI4Mi00N2U2LWJkODgtODJkNjVmYTFiNTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyMzkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YmU4ZDU4NmM5NWEwNWQwODRjMDQyMWUxMGUzZjdkOTBjMDVjMzA3Y2U1NDEyMjU1NjllMTU1MmI2ZjA3ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VkjBcPv18BuPyC_OGoSnS_keOrcTroWrjZ_28Nm7uT8)
> > 打开/marewood/resources/repositories/1/package.json：没有这样的文件或目录
> 
> 你的前端项目(仓库id1)下是否有package.json文件？marewood需要解析这个文件，才能提供文件夹给命令你选择。

目前是多目录模式 

```
├─xxx
│  ├─pkg
│  ├─...
└─xxx
   ├─pkg
   ├─...
```
