### ISSUE TITLE
docker 很方便，但是搭建成功之后，不知道如何下手，添加仓库也不顶用，拉取不下来代码

### ISSUE THREAD

**Issue by mrandpz** [xusenlin/marewood#7]
有空把教程写的详细点么 =。=

**Comment by xusenlin** [comment]
> 有空把教程写的详细点么 =。=

好的，后续会在整理一份。
针对你的问题，添加仓库之后代码拉取失败的话留意下终端输出的提示，如果你的仓库是私密的，那么必须要添加用户和密码让marewood有权限拉取代码。
